### ISSUE TITLE
Types for typescript

### ISSUE THREAD

**Issue by chamini2** [adamreisnz/sendgrid-mailer#1]
I would like to use this package for setting up a mailer. Is there any chance you'll add types for it? Or perhaps accept a PR with them?

**Comment by chamini2** [comment]
It would be easy by using the [sendgrid package](https://github.com/sendgrid/sendgrid-nodejs) types ([here](https://www.npmjs.com/package/@types/sendgrid)).

**Comment by adamreisnz** [comment]
@chamini2 thanks for the suggestion. I'm quite reluctant to create types myself, as I don't want to run into the same issues the folk at Moment were having -- having to maintain types which they know very little about, causing breaking changes in minor versions, etc.

I realise more and more people are starting to use TypeScript, and while I have used it myself as well, I still prefer plain vanilla javascript (ES6/7) without the added complexity of types.

As such, I'd be willing to add them in, but I wouldn't want to be actively maintaining them. If you're happy to create them and maintain them occasionally if I update this package, then you're welcome to create a PR though!

**Comment by chamini2** [comment]
Hey @adamreisnz, I totally understand you. I was creating a PR in [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) but it seems the type definitions for the sendgrid package don't work well. Maybe I will look into it in the future.

**Comment by adamreisnz** [comment]
Alright, no problem!

**Comment by adamreisnz** [comment]
Will close this for the time being, let me know if you need any help setting up the types.
