### ISSUE TITLE
Issue with FS dependency

### ISSUE THREAD

**Issue by gustavobissolli** [adamreisnz/sendgrid-mailer#5]
Hey guys! 

I have a application built on webpack and VueJS2! I am trying to use this library to send email through sendgrid and I have the following problem:

```
This dependency was not found:
* fs in ./~/sendgrid/lib/helpers/inbound/parse.js, ./~/mime/mime.js and 1 other
To install it, you can run: npm install --save fs
```

I've already run `npm install --save fs` and it's still same problem!

It's a client application... could be that the problem?

**Comment by adamreisnz** [comment]
@gustavobissolli it's probably best if you raise this issue at the official [sendgrid for node](https://github.com/sendgrid/sendgrid-nodejs/) repo, as it seems it's sendgrid dependencies that are missing somehow. This package is just a small wrapper around it.

We are [working on a new and improved API](https://github.com/sendgrid/sendgrid-nodejs/pull/378) for the official library though.

**Comment by gustavobissolli** [comment]
Thanks adam =)

I've added there... just posted here as well in case somebody has any clue!

Once I found a solution I can add here as well if you don't mind!

**Comment by adamreisnz** [comment]
Sure thing, no problem!
